<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.localink</groupId>
        <artifactId>localink</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>localink-delay-starter</artifactId>
    <name>localink-delay-starter</name>
    <description>延迟队列框架：Redisson 延迟队列分片 + 线程池消费</description>
    <dependencies>
        <dependency>
            <groupId>com.localink</groupId>
            <artifactId>localink-common</artifactId>
        </dependency>
    </dependencies>
</project>
